version: '3.8'
services:
  ipfs:
    image: "ipfs/go-ipfs:release"
    networks:
      - my-net
    
    command: daemon --enable-pubsub-experiment
      
      
  odbc-ipfs:
    image: "gonode"
    networks:
      - my-net
    
networks:
  my-net:
    driver: bridge
